// servpips-example: exec
// servpips-example: args=--servpips
/* SERVPIPS WP3 test (decision D-R2-2), concrete execution (with --servpips:
   ES StringToNumber, E16): the defined
   builtins js.tostring / js.toboolean / js.looseeq (through __servpips_fn)
   and the JS operators String(v), !!v and == agree with Node on concrete
   primitive values. Expected values were computed by Node v20.20.2
   (public.ecr.aws/lambda/nodejs) on the same synthetic values. Throws (rc != 0)
   on a mismatch. Generated by a script of the WP3 round-2 scratch area
   (values and expectations are all synthetic). */
var V = ["", "abc", "0", "5", "12", "007", " 12 ", "1.5", "0x10", "Infinity", "NaN", "true", "null", " ", 0, -0, 1, 5, 12, 1.5, -2.25, 1e+21, 123456789, NaN, Infinity, -Infinity, true, false, null, undefined];
var S = ["","abc","0","5","12","007"," 12 ","1.5","0x10","Infinity","NaN","true","null"," ","0","0","1","5","12","1.5","-2.25","1e+21","123456789","NaN","Infinity","-Infinity","true","false","null","undefined"];
var B = "011111111111110011111110111000";
var L = ["100000000000001100000000000100","010000000000000000000000000000","001000000000001100000000000100","000100000000000001000000000000","000010000000000000100000000000","000001000000000000000000000000","000000100000000000100000000000","000000010000000000010000000000","000000001000000000000000000000","000000000100000000000000100000","000000000010000000000000000000","000000000001000000000000000000","000000000000100000000000000000","000000000000011100000000000100","101000000000011100000000000100","101000000000011100000000000100","000000000000000010000000001000","000100000000000001000000000000","000010100000000000100000000000","000000010000000000010000000000","000000000000000000001000000000","000000000000000000000100000000","000000000000000000000010000000","000000000000000000000000000000","000000000100000000000000100000","000000000000000000000000010000","000000000000000010000000001000","101000000000011100000000000100","000000000000000000000000000011","000000000000000000000000000011"];
var bad = 0;
function check(what, got, exp) { if (got !== exp) { bad++; } }
for (var i = 0; i < V.length; i++) {
  check("tostring " + i, __servpips_fn("js.tostring", V[i]), S[i]);
  check("String " + i, String(V[i]), S[i]);
  check("toboolean " + i, __servpips_fn("js.toboolean", V[i]), B.charAt(i) === "1");
  check("!! " + i, !!V[i], B.charAt(i) === "1");
  for (var j = 0; j < V.length; j++) {
    check("looseeq " + i + " " + j, __servpips_fn("js.looseeq", V[i], V[j]), L[i].charAt(j) === "1");
    check("== " + i + " " + j, V[i] == V[j], L[i].charAt(j) === "1");
  }
}
if (bad !== 0) { throw new Error("mismatches: " + bad); }
